#
# Description:
# ------------
#
# This is a small test case that creates an enterprise manager with its database,
# a webview and a small sample EPAgent that sends data (to verify that the
# setup is valid)
#

em:
  image: apm-em
  links:
    - db:db
  ports:
    - "5001:5001"
    - "8081:8081"
  environment:
    - HEAP="2048m"
  volumes:
    # management module location
    - ~/mm:/root/Introscope/config/modules

db:
  image: apm-postgres

webview:
  image: apm-webview
  links:
    - em:em
  ports:
    - "8080:8080"
  hostname: apm-webview

sample:
  image: apm-sample:10.7.0-SP3
  links:
    - em:em
